name: hiro-ace-clean
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - dask
  - netcdf4
  - h5netcdf
  - zarr
  - gcsfs
  - scipy
  - matplotlib
  - tqdm
  - pyyaml
  - pip
